Update report path

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -106,22 +106,17 @@ jobs:
       - name: Run Unit Tests
         run: dotnet test HomeInventory.Tests --filter "Category=Unit" -c Release -v minimal --collect:"XPlat Code Coverage;CollectCoverage=true;Format=json,lcov,cobertura,opencover;SkipAutoProps=true;IncludeTestAssembly=false;ExcludeByFile=\"**/*.g.cs\"" --logger trx --results-directory ./coverage
         working-directory: ./src/HomeInventory
-      - name: Run Architecture Tests
-        if: success() || failure() # run this step even if previous step failed
-        run: dotnet test HomeInventory.Tests --filter "Category=Architecture" -c Release -v minimal --logger trx --results-directory ./coverage
-        working-directory: ./src/HomeInventory
-      - name: Save test results to artifacts
-        uses: actions/upload-artifact@v3 # upload test results
-        if: success() || failure() # run this step even if previous step failed
-        with:
-          name: test-results
-          path: coverage
       - uses: dorny/test-reporter@v1.6.0
+        if: success() || failure() # run this step even if previous step failed
         with:
           artifact: test-results # artifact name
           name: Unit tests # Name of the check run which will be created
-          path: "*.trx" # Path to test results (inside artifact .zip)
+          path: "./coverage/*.trx" # Path to test results
           reporter: dotnet-trx # Format of test results
+      - name: Run Architecture Tests
+        if: success() || failure() # run this step even if previous step failed
+        run: dotnet test HomeInventory.Tests --filter "Category=Architecture" -c Release -v minimal
+        working-directory: ./src/HomeInventory
       - name: Collect Coverage
         run: cp coverage/**/coverage.cobertura.xml coverage.cobertura.xml
         working-directory: ./src/HomeInventory
